function random_question() {
  var myArray = [
    "1. How do you express valuing someone?",
    "2. How do you know you are comfortable around someone?",
    "3. Who has influenced you most in life?",
    "4. What are you defining moments in life?",
    "5. How do you think of yourself?",
    "6. Who is the person you go to when you have a bad day?",
    "7. What is something that can instantly make you cry?",
    "8. What is your biggest insecurity?",
    "9. What do you think is your best trait/what are you most confident about?",
    "10. How did you get your scars?",
    "11. What is your life philosophy?",
    "12. Any regrets?",
    "13. Do you have a birthmark?",
    "14. What is a dream you have that you don't get to talk about much?",
    "15. Cookies or cookie dough/brownies or brownie batter?",
    "16. What are you most scared of?",
    "17. What is your guilty pleasure/relief?",
    "18. What's different between you and most other people?",
    "19. What are 5 things that make you smile?",
    "20. What do you want to be most remembered for?",
    "21. What is a common misconception people have of you?",
    "22. What is something you have learned about yourself?",
    "23. What is something simple that makes you happy?",
    "24. What is your biggest hope in life?",
    "25. When is the last time you did something for the first time?",
    "26. What is something that amazes you?",
    "27. Who has made you cry from being so excited to see them?",
    "28. What can give you goosebumps?",
    "29. What's your favorite thing about people?",
    "30. Do you like watching the movie trailer previews?",
    "31. Who is the closest friend you've ever had? Describe that relationship.",
    "32. Do you save old greeting cards and letters, or throw them all away? Why?",
    "33. How important is it to you that people pronounce/spell/remember your name correctly? Why?",
    "34. Where is a place you have connected with?",
    "35. When are you shy?",
    "36. What's the most important thing about you?",
    "37. How do you say goodbye to people?",
    "38. What's your favorite subject to discuss?",
    "39. What are the top 3 qualities that draw you to someone new?",
    "40. What's the best advice you've ever been given?",
    "41. How would you summarize the highs and lows of your week?",
    "42. What event in life has brought about the biggest life change?",
    "43. If you could say anything to the people you're with right now, what would you say?",
    "44. How would you describe the perfect day?",
    "45. Favorite quote?",
    "46. What scares you most about the future?",
    "47. What would make you totally content right now?",
    "48. What silly thing have you done in the name of love?",
    "49. What was the happiest era of your life?",
    "50. When did you ever 'click' with someone you just met? What qualities do you attribute to the connection?",
    "51. When you are happy, how do you like to celebrate?",
    "52. Who is a good listener in your life? Who is a bad listener?",
    "53. What is one of the greatest compliments you could receive?",
    "54. Do you think you're leading a fulfilling life?",
    "55. Is it more important to have your close friends think highly of you or acquaintances?",
    "56. Worst date? Best/ideal date?",
    "57. What is your go-to drink?",
    "58. What would be your three wishes from a genie?",
    "59. What energizes you?",
    "60. What would make life easier for you as of lately?",
    "61. What has made you laugh today?",
    "62. Have you done anything lately that has made you proud of yourself?",
    "63. What have you learned lately that you found interesting?",
    "64. What are three things you want someone to take away from a first impression of you?",
    "65. What are things you're willing to spend money on?",
    "66. If you could change anything about the way you were raised, what would it be?",
    "67. What superpower would you want?",
    "68. When did you last cry in front of another person? By yourself?",
    "69. What one item would you save from your house burning down?",
    "70. Are you an introvert or extrovert?",
    "71. What is your love language?",
    "72. What do you want out of a relationship?",
    "73. Does 'sorry' or 'thank you' mean more?",
    "74. What's the best advice you can give someone?",
    "75. How do you handle surprises?",
    "76. What stresses you out?",
    "77. What was your dream job as a kid?",
    "78. What is something crazy that you've done (by your definition of crazy)?",
    "79. If you had a week or less to live, how would you live it?",
    "80. What is your biggest disparity in life?",
    "81. What separates a good friend from a great friend?",
    "82. If money wasn't an issue, what would you choose to do with your life?",
    "83. Is there any reason for your phone background?",
    "84. What makes you feel the most free?",
    "85. What is the model you set for the way that you're living your life?",
    "86. What is something everyone knows about you?",
    "87. If you were to create a music festival, what bands would you bring in?",
    "88. What do you have brand loyalty towards?",
    "89. What is a deal breaker for you in relationships?",
    "90. When was a moment you felt loved?",
    "91. What are you bashful about?",
    "92. When did you last feel lonely?",
    "93. What is something you're working on for yourself/personal development?",
    "94. What role does music have in your life?",
    "95. What is something you do before every date?",
    "96. What's the best birthday you've ever had?",
    "97. What is one of your never have I evers?",
    "98. How do people normally describe you?",
    "99. What would be one item to add to a museum exhibition of your life?",
    "100. When was your 15 minutes of fame?",
    "101. What's the reason for your name?",
    "102. What is one of your bad habits?",
    "103. How did you find out about Santa?",
    "104. Would you rather be the one leaving or the one left?",
    "105. What is your personal TOMA (top of mind awareness) in other people’s eyes/minds?",
    "106. What is something on your bucket list?",
    "107. What's one thing about your life you would never change for someone?",
    "108. How do you deal with rejection?",
    "109. When was the last time your life changed in a single day?",
    "110. What is the last risk you took?",
    "111. What has been a painful loss for you?",
    "112. How do you handle when you're wrong?",
    "113. If you were asked to be interviewed, what event/accomplishment/position/etc would it be for? (Can be past, present, or future ambition)",
    "114. Would you live in another country?",
    "115. If you were about to go deaf, what would be the last thing you’d want to hear?",
    "116. What is something that keeps you up at night?",
    "117. What is your “why”?",
    "118. Which is more powerful to you: being the source of someone’s happiness or source of their sadness?",
    "119. Have you ever been homesick for a person?",
    "120. What is a recurring thought/internal dialogue you have from something someone said to you?",
    "121. What inspires you?",
    "122. What is a quality in people that you admire?",
    "124. 124. Who is the most fascinating person you’ve never met?",
    "125. How have you changed as a person since your previous phase of life?",
    "126. How often do you say what you really want to say?",
    "127. Do you like to catch up with people better through frequent short texts or infrequent long calls?",
    "128. What is one of the greatest insults to you?",
    "130. 130. Have you had a change in perspective in anything lately?",
    "131. Who are you in your public life vs your private life?",
    "132. What do you want to be loved for?",
    "133. Do you have any lost skills?",
    "134. How do you react to someone else’s bad/sad news?",
    "135. What would you want in a dream work environment?",
    "136. When was a fulfilling moment you had at work?",
    "137. When was a time you felt doubtful at work? Did you get to talk to anyone about it?",
    "138. Do you have a favorite word?",
    "139. How is your day today different from yesterday?",
    "140. What three things would you want to be free for the rest of your life?",
    "141. What is your next big thing that you’re looking forward to?",
    "142. Where/in what do you find protection?",
    "143. What do you do to show yourself self-love?",
    "144. What disappoints you or makes you frown? (Not getting to see sunsets in their prime; when live versions of songs aren’t as good as the recording)",
    "145. What aspect of your life do you think people would want? What aspect do you think they wouldn’t want?",
    "146. Who in this life makes you feel the most worthwhile?",
    "147. What is one thing that people wouldn’t know from looking at a picture of you?",
    "148. Do your obsession(s) align with your passion(s)?",
    "149. Who are you outside of your job (aka do you have an identity outside of accomplishment)?",
    "150. Do you prefer sunrises or sunsets?"
  ];

  var randomItem = myArray[Math.floor(Math.random()*myArray.length)];

  document.getElementById('bi_content').innerHTML = randomItem
}


document.getElementById('bi_button').onclick = random_question;
